POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title":"Hitchikers Guide to the Galaxy",
    "author": "Douglas Adams",
    "url": "somewhere",
    "likes": "1111111111"
}
